### ISSUE TITLE
jsコードにある「var 」を「let」に変更

### ISSUE THREAD

**Issue by Akaota** [gwangh91/mailProject#11]
「var 」、「let」、「const」について調査する。

**Comment by gwangh91** [comment]
「var 」、「let」、「const」について調査

1.スコープ
 スコープとは、宣言した変数を利用できる範囲
 
  -var：関数スコープ
  -let：ブロックスコープ
  -const：ブロックスコープ

2.変数宣言方式
-var：再宣言、再代入のどちらも可能
-let：再宣言できない、再代入できる
-const：どちらも不可能

3.ホイスティング
 var宣言文やfunction宣言文などを当該スコープの先頭に移したように動作する特性

  -var
    変数宣言文の前に変数を参照することができる
  -let、const
    変数宣言文以前に変数を参照できない


let使用理由
 ブロックスコープを使う、再割り当て可能、ホスティング防止するため、let使用

プロジェクトに適用（変更済）
mailFormScript.jsファイルに「var」→「let」に変更
